### ISSUE TITLE
KeyError: 2

### ISSUE THREAD

**Issue by morganne00** [RussellSB/voice-conversion-gan#13]
Hello, 
Congratulations, and thank you for sharing this very interesting project. We are trying to run this project, and have completed the data preparation and preprocessing steps. But at the training step we run into an issue. We have 2 speakers and are otherwise using the default settings. The printout from the run is pasted below. 
```
Namespace(b1=0.5, b2=0.999, batch_size=4, channels=1, checkpoint_interval=1, dataset='../data/data_urmp/', decay_epoch=50, dim=32, epoch=0, img_height=128, img_width=128, lr=0.0001, model_name='test', n_cpu=8, n_downsample=2, n_epochs=100, n_spkrs=2, plot_interval=1)
2 2
Cuda found.
/path_cropped/venv/pytorch/lib/python3.8/site-packages/torch/optim/adam.py:48: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adam, self).__init__(params, defaults)
  0%|                                                                                        | 0/2136 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train_global()
  File "train.py", line 267, in train_global
    losses = train_local(i, epoch, batch, pair[0], pair[1], losses)
  File "train.py", line 151, in train_local
    X1 = Variable(batch[id_1].type(Tensor))
KeyError: 2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/path_cropped/venv/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/path_cropped/venv/pytorch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
```
The machine we use has an RTX 3080 GPU, and a CPU with 14 cores / 28 threads.
We have also tried to decrease the number of cpu's to 1 and 2, for example, and the error is similar, but shorter: 

```
Namespace(b1=0.5, b2=0.999, batch_size=4, channels=1, checkpoint_interval=1, dataset='../data/data_urmp/', decay_epoch=50, dim=32, epoch=0, img_height=128, img_width=128, lr=0.0001, model_name='test', n_cpu=1, n_downsample=2, n_epochs=100, n_spkrs=2, plot_interval=1)
2 2
Cuda found.
/path_cropped/venv/pytorch/lib/python3.8/site-packages/torch/optim/adam.py:48: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adam, self).__init__(params, defaults)
  0%|                                                                                        | 0/2136 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train_global()
  File "train.py", line 267, in train_global
    losses = train_local(i, epoch, batch, pair[0], pair[1], losses)
  File "train.py", line 151, in train_local
    X1 = Variable(batch[id_1].type(Tensor))
KeyError: 2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```
Just in case, we have also reduced the batch size to 1 and 2, and then it stops at `KeyError: 2` already.
Can you, or someone else, please help with that the problem is and how to resolve it?

**Comment by morganne00** [comment]
Problem resolved, by changing line 49 from:
`transfer_combos = list(itertools.combinations(range(2, 4), 2))`
to:
`transfer_combos = [(0, 1)]`
and some related downstream modifications.
